### ISSUE TITLE
OSError: Sorry, your environment is not currently supported! system='Linux' machine='x86_64'

### ISSUE THREAD

**Issue by b10815061** [FHPythonUtils/PyRlottie#2]
## Question

- [v] I have read the comment above and have completed each step

Hello! Thanks for the awesome works of this library. I am currently using it to convert .tgs to .gif so as to render the telegram sticker in front-end.

I am currently using a windows OS and it works just excellent and behaves as expect.

But when I build a docker image of Linux x86_64 ( I suppose it is supported according to the [documentation](https://pypi.org/project/pyrlottie/)?)  and try to run the same code on it, the build failed.

Below is some information of my environment (in docker) and the error log. 

Am I misunderstanding anything? 

![image](https://user-images.githubusercontent.com/65760907/191305484-6a6d17e8-5c27-4830-973b-0ec155ddbc24.png)

![image](https://user-images.githubusercontent.com/65760907/191305548-3baa5c85-f4e2-4636-b242-e59d24782796.png)

**Comment by b10815061** [comment]
UPDATE : 

After some investigation, I think that I've narrow down the situation. 

The above error ALSO OCCURS in the windows environment WHEN I use ```pyinstaller``` to compile my code into an executable, so I suppose there's something related to it? (Is there any workarounds?)

And also I've tried launch my project using a python script format ( i.e. ``` $ python main.py ``` ) in my linux x86_64 image.

But it raised another runtime error as below, I've tried to trace code inside of the ```__init__.py``` file but barely understand it.
(There's no error if I run it in the windows environment with python script format)

Appreciate any kind of help, thanks!

![image](https://user-images.githubusercontent.com/65760907/191320164-e81075fe-c5e6-4c85-a6fc-3977f182315b.png)

**Comment by b10815061** [comment]
[SOLVED]

Hey! For those encountering same problem with me. here's the solution : 

For the first situation, which is caused by using ```pyinstaller```, the issue is triggered because the ```pyinstaller``` packages our whole project, and so the location of this (```pyrlottie```) dependency has changed. We can trace the source code of the error, which will lead us to ```__init__.py``` line 187, the if condition failed since it couldn't find a matching folder. ***In this case, the statement failed because ```pyinistaller``` packaged my project and so the folder does not even exist, thus the function raised the error***.

For the second situation, it is quite easy, Linux system has a strict permission policy, check these executables :  ```gif2webp``` and ```lottie2gif``` under your ```\usr\local\lib\pythonx\site-packages\pyrlottie\<folder_corresponding_to_your_OS>```, do they have permission to execute? 

( 
tips 1 : to check your OS platform -> open python console, ```import os``` , ```print(os.uname())```
tips 2 : to check the location of site-packages -> open python console, ```import sys```, ```print(sys.path)```
tips 3 : to check the permission of the files -> cd to the directory, then ```$ls -l```
tips 4 : in this case, ```$chmod 777 <file_name>``` or ```chmod +x <file_name>``` fixes the issue
)

**Comment by RedGuys** [comment]
For those who also came to this issue from Google, on Windows (confirmed by personal experience), a similar problem may occur if you run a script from another process without explicitly passing environment variables.

An exception will throw: `Sorry, your environment is not currently supported! system='Windows' machine=''`.
As a quick fix, you can explicitly specify the architecture in the environment variables by using `PROCESSOR_ARCHITECTURE` env from the location where you run the script, in my case Node.js:
```js
subprocess.execSync(`start ${PYTHON} lottieSplit.py`, {
    env: {
        "PROCESSOR_ARCHITECTURE": "amd64",
    },
    shell: true
});
```
